{
    "addison state senate district": "50ADD",
    "addison": "50ADD",
    "bennington state senate district": "50BEN",
    "bennington": "50BEN",
    "caledonia state senate district": "50CAL",
    "caledonia": "50CAL",
    "grand-isle-chittenden state senate district": "50CGI",
    "grand-isle-chittenden": "50CGI",
    "chittenden state senate district": "50CHI",
    "chittenden": "50CHI",
    "essex-orleans state senate district": "50E-O",
    "essex-orleans": "50E-O",
    "franklin state senate district": "50FRA",
    "franklin": "50FRA",
    "lamoille state senate district": "50LAM",
    "lamoille": "50LAM",
    "orange state senate district": "50ORA",
    "orange": "50ORA",
    "rutland state senate district": "50RUT",
    "rutland": "50RUT",
    "washington state senate district": "50WAS",
    "washington": "50WAS",
    "windham state senate district": "50WDM",
    "windham": "50WDM",
    "windsor state senate district": "50WSR",
    "windsor": "50WSR"
}
